const products = [
  // Electronics Data
  {
    id: 1,
    name: "Airpods_Pro Wireless Earbuds Bluetooth 5.0 Compatible with IOS and Android",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/airpods-1.png",
  },
  {
    id: 2,
    name: "New K8 Type C Wireless Microphone K8 Collar Mic For Type C - Noise Callaction Reduction Mic 20 Meter Long Range Wireless Mic for Phone For Mobile Phone Camera_iphone K8 MICROPHONE Mic",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/airpods-2.png",
  },
  {
    id: 3,
    name: "M10 True Wireless Earbuds Airpods M10 Air buds : Bluetooth with Noise-Cancelling, Long Battery Life & Touch Control - Perfect for Sports & Gaming",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/airpods-3.jpg",
  },
  {
    id: 4,
    name: "Original Air31 Air pro Air buds Wireless Earbuds Bluetooth Airpods Earphone Transparent HIFI Headphones LED 3500 MAH Power Digital Display Stereo Sound Earphones",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/airpods-4.png",
  },
  {
    id: 5,
    name: "Lenovo N22/N23 Chromebook – 11.6″ – 4 GB RAM – 16 GB ROM – With Play Store - PUBG Supported - Daraz like new laptops",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-1.webp",
  },
  {
    id: 6,
    name: "Dell 3180 Chromebook 11.6 inches HD screen, 4GB Ram 16GB SSD, HDMI, WiFi, Webcam, Chrome OS -",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-2.webp",
  },
  {
    id: 7,
    name: " Elitebook 820 g3 - Core i5 6th Generation - 8GB RAM - 128GB SSD + 500GB HDD- 14inch Screen - FREE LAPTOP BAG (WINDOWS 11 REGISTERED) - Daraz like new laptops",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-3.webp",
  },
  {
    id: 8,
    name: '" HP ProBook 650G4 I5 8th Gen 16gb Ram 128gb ssd+500gb hdd 15.6" Screen (Windows 11 Activated) & Free Laptop Bag - Daraz like new laptops',
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-4.webp",
  },
  {
    id: 9,
    name: "Dell 3180 CB 11.6 inches HD screen, 4GB Ram 16GB SSD, HDMI, WiFi, Webcam, Chrome OS -",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-5.webp",
  },
  {
    id: 10,
    name: "Dell Latitude E7280 - Core i5 7th Generation - 8GB DDR4 RAM - 256GB SSD - 12.5inch Screen - Windows 11 Licensed (FREE LAPTOP BAG) - Daraz like new laptops",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-6.webp",
  },
  {
    id: 11,
    name: "Lenovo N22/N23 Chromebook – 11.6″ – 4 GB RAM – 16 GB ROM – With Play Store - PUBG Supported",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-7.webp",
  },
  {
    id: 12,
    name: "HP Chromebook 11 G4 | 16GB Storage | 4GB RAM | 11.6″ Display | Playstore Supported Chromebook | Black - Daraz Like New Laptops",
    price: 499.99,
    category: "electronics",
    image: "./img/electronics/laptop-8.webp",
  },
      // Nove;/books Data 
  {
    id: 13,
    name: "peer-E-Kamil",
    price: 9.99,
    category: "books",
    image: "./img/books/book-1.webp",
  },

  {
    id: 14,
    name: "Ab-E-Hayyat",
    price: 9.99,
    category: "books",
    image: "./img/books/book-2.webp",
  },
  {
    id: 15,
    name: "Mala",
    price: 9.99,
    category: "books",
    image: "./img/books/book-3.webp",
  },
  {
    id: 16,
    name: "Jannat K Patty",
    price: 9.99,
    category: "books",
    image: "./img/books/book-4.webp",
  },
  {
    id: 17,
    name: "Halim",
    price: 9.99,
    category: "books",
    image: "./img/books/book-5.webp",
  },
  {
    id: 18,
    name: "Namal",
    price: 9.99,
    category: "books",
    image: "./img/books/book-6.webp",
  },
  {
    id: 19,
    name: "Karakaram Ka Taj Mahel",
    price: 9.99,
    category: "books",
    image: "./img/books/book-7.webp",
  },
  {
    id: 20,
    name: "Hunting Adeline",
    price: 9.99,
    category: "books",
    image: "./img/books/book-8.webp",
  },
  {
    id: 21,
    name: "Haunting Adeline",
    price: 9.99,
    category: "books",
    image: "./img/books/book-9.webp",
  },
     // Clothing Data
  {
    id: 22,
    name: "Grey Color Stylish Front Pocket Shirt Style Coat",
    price: 40.45,
    category: "clothing",
    image: "./img/clothes/c-1.webp",
  },
  {
    id: 23,
    name: "Bold Street Store -  Olive Half Sleeve Puffer Jacket with Black Hood",
    price: 35.45,
    category: "clothing",
    image: "./img/clothes/c-2.webp",
  },
  {
    id: 24,
    name: "Olive Sleeveless Zipper with Grid Pattern",
    price: 30.56,
    category: "clothing",
    image: "./img/clothes/c-3.jpg",
  },
  {
    id: 25,
    name: "Maroon Zipper Sweat Shirt with Black Rib and Collar",
    price: 19.99,
    category: "clothing",
    image: "./img/clothes/c-4.jpg",
  },
  {
    id: 26,
    name: "Button Down Plum Dress",
    price: 20.87,
    category: "clothing",
    image: "./img/clothes/c-5.webp",
  },
  {
    id: 27,
    name: "Firty Lilac Dress",
    price: 30.56,
    category: "clothing",
    image: "./img/clothes/c-6.webp",
  },
  {
    id: 28,
    name: "Flirty NavyBlue Floral",
    price: 25.67,
    category: "clothing",
    image: "./img/clothes/c-7.webp",
  },
  {
    id: 29,
    name: "Black Lavish Kaftan",
    price: 31.56,
    category: "clothing",
    image: "./img/clothes/c-8.webp",
  },
  //----------------- Gym Supplements Data ------------------//
  //----------------- Gym Supplements Data ------------------//
  //----------------- Gym Supplements Data ------------------//
 
  {
    id: 30,
    name: "Nitro-Tech Protein Powder",
    price: 17.89,
    category: "gym",
    image: "./img/supplements/s-img-1.avif",
  },
  {
    id: 31,
    name: "Nitro-Tech 100% Whey Gold",
    price: 23.45,
    category: "gym",
    image: "./img/supplements/s-img-2.avif",
  },
  {
    id: 32,
    name: "100% Mass Gainer",
    price: 22.67,
    category: "gym",
    image: "./img/supplements/s-img-3.avif",
  },
  {
    id: 33,
    name: "Platinum 8-Hour Protein",
    price: 26.00,
    category: "gym",
    image: "./img/supplements/s-img-4.avif",
  },
  {
    id: 34,
    name: "Iso Whey Clear",
    price: 23.70,
    category: "gym",
    image: "./img/supplements/s-img-5.avif",
  },
  {
    id: 35,
    name: "Plant Protein",
    price: 24.34,
    category: "gym",
    image: "./img/supplements/s-img-6.avif",
  },
  {
    id: 36,
    name: "Cell-Tech",
    price: 27.35, 
    category: "gym",
    image: "./img/supplements/s-img-7.avif",
  },
  {
    id: 37,
    name: "Platinum 100% Creatine",
    price: 23.20,
    category: "gym",
    image: "./img/supplements/s-img-8.avif",
  },
];